export const START_GETTING_NEWS = 'START_GETTING_NEWS';
export const UPDATE_NEWS_DATA = 'UPDATE_NEWS_DATA';
export const UPDATE_NEWS_ERROR = 'UPDATE_NEWS_ERROR';
export const START_GETTING_ARTICLE = 'START_GETTING_ARTICLE';
export const UPDATE_ARTICLE_DATA = 'UPDATE_ARTICLE_DATA';
export const UPDATE_ARTICLE_ERROR = 'UPDATE_ARTICLE_ERROR';